[RITP] auto things and shooter map
frc-862/rhapsody pull request #551
Opened 2024-08-13 22:12 UTC by WindowsVistaisCool

I trust most path changes are fine. If shooter map works then great

## Good autos:
- `3-SF-[C2-C3]-EC`

## Autos that still need logic work:
- `3-SB-[F4-F3]-EF`: SCollect -> SCollectTele, CandSub -> SmartShoot
- `2-SB-[F4]-EF`: Could easily be turned into a 3 piece; needs more testing.
- `2-ST-[C1]-EC`: probably should be deleted, but will leave for now

2024-08-16 15:39 UTC, Meh243 reviewed
No problems that I have saw. Nice fix for teleop!

2024-08-17 03:44 UTC, HeeistHo requested changes
comment tune.

2024-08-17 03:44 UTC, HeeistHo commented on src/main/java/frc/robot/RobotContainer.java
> +		new Trigger(coPilot::getYButton).whileTrue(new Tune(flywheel, pivot));
comment this

2024-08-17 03:44 UTC, HeeistHo commented on src/main/java/frc/robot/command/SmartCollect.java
> +        if (isAutonomous || DriverStation.isAutonomous()) {
why is this needed?

2024-08-17 03:57 UTC, HeeistHo approved these changes
yay

2024-08-17 03:57 UTC, merged